[logging]
log_to_file = false # Enable/disable logging to a file (named <program>.log)
                    # Tip: on linux logging to the systemd journal is supported
stdout_debug = false # Enable debug logging level on stdout
file_debug = false # Enable debug logging level on the log file (if enabled)
                   # Note: not recommended, as debug log logs a lot of data
journal_debug = false # Enable debug logging level on the systemd journal (if enabled)

[autorx]
host = "localhost" # Host for payload summaries
port = 55673 # Port for payload summaries

[gpsd]
host = "localhost" # Host for payload summaries
port = 2947 # Port for payload summaries

[display]
driver = "ILI9341" # Display driver. Currently only the ILI9341 is supported
                   # "software" can also be used to display the image as a window on the host
flip_display = false # Wether to flip the display 180Â° or not
spi_port = 0 # SPI port
spi_device = 0 # SPI device
gpio_dc = 23 # Data/Command pin for 4 Wire SPI
gpio_rst = 24 # Reset pin

[touch]
driver = "XPT2046" # Touch driver. Currently only the XPT2046 is supported
spi_port = 1 # SPI port
spi_device = 0 # SPI device
cs_pin = 27 # Chip select pin
irq_pin = 26 # Interrupt request pin
